import { useState } from 'react';
import { buildEnrichedCSV, downloadCSV } from '../lib/exportHelpers';
import { Document, Page, Text, View, StyleSheet, pdf } from '@react-pdf/renderer';
import { LAYER_CONFIG } from '../lib/layerConfig';

const pdfStyles = StyleSheet.create({
  page: { padding: 32, fontFamily: 'Helvetica', fontSize: 10 },
  title: { fontSize: 18, fontFamily: 'Helvetica-Bold', marginBottom: 4, color: '#1c3557' },
  subtitle: { fontSize: 10, color: '#7a8fa6', marginBottom: 20 },
  sectionHeader: { fontSize: 12, fontFamily: 'Helvetica-Bold', color: '#1c3557', marginTop: 16, marginBottom: 6 },
  tableRow: { flexDirection: 'row', borderBottom: '1px solid #e2e8f0', paddingVertical: 3 },
  tableHeader: { flexDirection: 'row', borderBottom: '2px solid #1c3557', paddingBottom: 4, marginBottom: 2 },
  cell: { flex: 3 },
  cellRight: { flex: 1, textAlign: 'right' },
  headerCell: { flex: 3, fontFamily: 'Helvetica-Bold', color: '#1c3557' },
  headerCellRight: { flex: 1, fontFamily: 'Helvetica-Bold', color: '#1c3557', textAlign: 'right' },
  unmatched: { color: '#e63947' },
  footer: { marginTop: 24, fontSize: 8, color: '#a0aec0' },
});

function PDFReport({ layerSummary, activeLayers, pointCount, numericFields }) {
  const date = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  function getDisplayName(layerId) {
    if (LAYER_CONFIG[layerId]) return LAYER_CONFIG[layerId].displayName;
    if (layerId.startsWith('council-')) return `Council Districts (${layerId.replace('council-', '')})`;
    if (layerId.startsWith('custom-')) return `Custom: ${layerId.replace('custom-', '')}`;
    return layerId;
  }

  return (
    <Document>
      <Page size="LETTER" style={pdfStyles.page}>
        <Text style={pdfStyles.title}>District Mapper Report</Text>
        <Text style={pdfStyles.subtitle}>{date} · {pointCount.toLocaleString()} data points analyzed</Text>

        {activeLayers.map((layerId) => {
          const rows = layerSummary[layerId] || [];
          return (
            <View key={layerId}>
              <Text style={pdfStyles.sectionHeader}>{getDisplayName(layerId)}</Text>
              <View style={pdfStyles.tableHeader}>
                <Text style={pdfStyles.headerCell}>District</Text>
                <Text style={pdfStyles.headerCellRight}>Points</Text>
                <Text style={pdfStyles.headerCellRight}>% of Total</Text>
                {numericFields.slice(0, 2).map((f) => (
                  <Text key={f} style={pdfStyles.headerCellRight}>Avg {f}</Text>
                ))}
              </View>
              {rows.map((row, i) => (
                <View key={i} style={pdfStyles.tableRow}>
                  <Text style={pdfStyles.cell}>{row.districtName}</Text>
                  <Text style={pdfStyles.cellRight}>{row.count.toLocaleString()}</Text>
                  <Text style={pdfStyles.cellRight}>{row.pct}%</Text>
                  {numericFields.slice(0, 2).map((f) => (
                    <Text key={f} style={pdfStyles.cellRight}>
                      {row.fieldAverages[f] !== undefined ? row.fieldAverages[f].toFixed(2) : '—'}
                    </Text>
                  ))}
                </View>
              ))}
            </View>
          );
        })}

        <Text style={pdfStyles.footer}>Generated by District Mapper · North Arrow</Text>
      </Page>
    </Document>
  );
}

export default function ExportControls({
  originalRows,
  enrichedPoints,
  activeLayers,
  layerSummary,
  numericFields,
  pointCount,
  compact = false,
}) {
  const [pdfLoading, setPdfLoading] = useState(false);
  const disabled = activeLayers.length === 0;

  function handleCSV() {
    const csv = buildEnrichedCSV(originalRows, enrichedPoints, activeLayers);
    downloadCSV(csv);
  }

  async function handlePDF() {
    setPdfLoading(true);
    try {
      const doc = (
        <PDFReport
          layerSummary={layerSummary}
          activeLayers={activeLayers}
          pointCount={pointCount}
          numericFields={numericFields}
        />
      );
      const blob = await pdf(doc).toBlob();
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = 'district-mapper-report.pdf';
      link.click();
      URL.revokeObjectURL(url);
    } finally {
      setPdfLoading(false);
    }
  }

  if (compact) {
    return (
      <>
        <button style={btnPrimary} onClick={handleCSV} disabled={disabled} title="Download Enriched CSV">
          CSV
        </button>
        <button style={btnSecondary} onClick={handlePDF} disabled={disabled || pdfLoading} title="Download PDF Report">
          {pdfLoading ? '…' : 'PDF'}
        </button>
      </>
    );
  }

  return (
    <div style={container}>
      <button style={btnPrimary} onClick={handleCSV} disabled={disabled}>
        Download Enriched CSV
      </button>
      <button style={btnSecondary} onClick={handlePDF} disabled={disabled || pdfLoading}>
        {pdfLoading ? 'Generating…' : 'Download PDF Report'}
      </button>
      {disabled && (
        <span style={hintStyle}>Enable at least one boundary layer to export</span>
      )}
    </div>
  );
}

const container = {
  display: 'flex', gap: 8, alignItems: 'center',
  padding: '8px 12px', borderTop: '1px solid #dde3ea', flexShrink: 0, flexWrap: 'wrap',
};
const btnPrimary = {
  padding: '6px 14px', background: 'var(--dark-navy)', color: '#fff',
  border: 'none', borderRadius: 4, fontSize: 12, fontWeight: 600, cursor: 'pointer',
};
const btnSecondary = {
  padding: '6px 14px', background: 'var(--off-white)', color: 'var(--dark-navy)',
  border: '1px solid var(--mid-blue)', borderRadius: 4, fontSize: 12, fontWeight: 600, cursor: 'pointer',
};
const hintStyle = { fontSize: 11, color: '#7a8fa6' };
