import { Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';

const s = StyleSheet.create({
  page:        { padding: 36, fontFamily: 'Helvetica', fontSize: 10, color: '#222' },
  header:      { marginBottom: 20, borderBottom: '2px solid #1c3557', paddingBottom: 12 },
  title:       { fontSize: 18, fontFamily: 'Helvetica-Bold', color: '#1c3557', marginBottom: 4 },
  meta:        { fontSize: 9, color: '#7a8fa6' },
  mission:     { fontSize: 10, color: '#333', fontStyle: 'italic', marginTop: 6, lineHeight: 1.5 },
  countLine:   { fontSize: 9, color: '#7a8fa6', marginBottom: 16 },
  card:        { marginBottom: 14, borderLeft: '4px solid #ccc', paddingLeft: 10, paddingTop: 4, paddingBottom: 4 },
  cardHigh:    { borderLeft: '4px solid #e63947' },
  cardMid:     { borderLeft: '4px solid #f5a800' },
  cardLow:     { borderLeft: '4px solid #467c9d' },
  titleRow:    { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 4 },
  scorePill:   { fontSize: 9, fontFamily: 'Helvetica-Bold', color: '#fff',
                 backgroundColor: '#467c9d', borderRadius: 3, padding: '2 6' },
  scorePillHi: { backgroundColor: '#e63947' },
  scorePillMd: { backgroundColor: '#f5a800' },
  billId:      { fontSize: 10, fontFamily: 'Helvetica-Bold', color: '#1c3557', flex: 1 },
  summary:     { fontSize: 9, color: '#333', lineHeight: 1.5, marginBottom: 3 },
  reason:      { fontSize: 9, color: '#555', fontStyle: 'italic', marginBottom: 3 },
  actionBox:   { backgroundColor: '#f7f9fc', padding: '4 6', borderRadius: 2, fontSize: 9, color: '#1c3557' },
  status:      { fontSize: 8, color: '#888', marginBottom: 4 },
  repBadge:    { fontSize: 8, color: '#1c3557', fontFamily: 'Helvetica-Bold', marginBottom: 4 },
  footer:      { marginTop: 24, fontSize: 8, color: '#a0aec0', textAlign: 'center' },
});

export default function PolicyPDFDoc({ bills, districtName, mission, savedAt }) {
  const date = savedAt || new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return (
    <Document>
      <Page size="LETTER" style={s.page}>
        <View style={s.header}>
          <Text style={s.title}>Policy Pulse — {districtName}</Text>
          <Text style={s.meta}>{date} · District Mapper by North Arrow</Text>
          {mission ? <Text style={s.mission}>"{mission}"</Text> : null}
        </View>

        <Text style={s.countLine}>
          {bills.length} relevant bill{bills.length !== 1 ? 's' : ''} · Ranked by relevance
        </Text>

        {bills.map((bill) => {
          const isHigh = bill.relevanceScore >= 80;
          const isMid  = bill.relevanceScore >= 50 && !isHigh;
          return (
            <View key={bill.id} style={[s.card, isHigh ? s.cardHigh : isMid ? s.cardMid : s.cardLow]}>
              <View style={s.titleRow}>
                <Text style={[s.scorePill, isHigh ? s.scorePillHi : isMid ? s.scorePillMd : {}]}>
                  {bill.relevanceScore}
                </Text>
                <Text style={s.billId}>{bill.identifier} — {bill.title}</Text>
              </View>
              {bill.sponsoredByYourRep && (
                <Text style={s.repBadge}>★ Sponsored by your district's rep</Text>
              )}
              <Text style={s.status}>
                {bill.status}{bill.lastActionDate ? ` · ${bill.lastActionDate}` : ''}
                {bill.primarySponsor ? ` · ${bill.primarySponsor}` : ''}
              </Text>
              <Text style={s.summary}>{bill.plainSummary}</Text>
              <Text style={s.reason}>{bill.relevanceReason}</Text>
              <View style={s.actionBox}>
                <Text>Action: {bill.suggestedAction}</Text>
              </View>
            </View>
          );
        })}

        <Text style={s.footer}>Generated by District Mapper · North Arrow · district-mapper.vercel.app</Text>
      </Page>
    </Document>
  );
}
